### ISSUE TITLE
Isolate command line options

### ISSUE THREAD

**Issue by fonsp** [JuliaPluto/Malt.jl#29]
I just merged https://github.com/JuliaPluto/Malt.jl/pull/26 because it matches Distributed behaviour, but we might actually want to not match Distributed here: we want to isolate most of the command line options used by the process from those used by the host.

So maybe revert #26

**Comment by fonsp** [comment]
Mosè suggested using `julia_cmd()[1]` to get the Julia command without flags using public API: https://github.com/JuliaLang/julia/issues/48393#issuecomment-1404032847

**Comment by savq** [comment]
Yep, that seems like the best solution.
