### ISSUE TITLE
Stop listening when TCP connection is established?

### ISSUE THREAD

**Issue by Pangoraw** [JuliaPluto/Malt.jl#41]
That's what lsp server/clients seems to do: https://youtu.be/DFAdG9o0sTw?t=690

Anyone who can connect to the worker TCP port can execute code. Maybe that's not a valid concern in our case ? And it is also only applicable with #32.

**Comment by fonsp** [comment]
Cool video! 

Is this already a security problem with Distributed then? Is it possible to send a message to the Distributed client from a browser, like the JSONRPC example in the video?

**Comment by Pangoraw** [comment]
> Is this already a security problem with Distributed then?

It uses a cookie shared between all nodes: https://github.com/JuliaLang/julia/blob/441c57057306ec63ed874e610bc53ba2a145c17e/stdlib/Distributed/src/process_messages.jl#L255 that is needed to connect to a worker.
This allows for secure Worker<->Worker communication without going through the main node.

**Comment by fonsp** [comment]
Ah I see, and it looks like they write this cookie over `stdin` to the worker before it starts the server:

https://github.com/JuliaLang/julia/blob/441c57057306ec63ed874e610bc53ba2a145c17e/stdlib/Distributed/src/cluster.jl#L711

Maybe we should also implement a cookie/password?
