### ISSUE TITLE
Feature Request: Add backtrace information to `RemoteException`

### ISSUE THREAD

**Issue by schlichtanders** [JuliaPluto/Malt.jl#66]
I am currently trying to figure out where this bug https://github.com/JuliaPluto/Malt.jl/issues/65 comes from.

Unfortunately, Malt.jl misses to print stacktraces. Pluto has perfect support for stacktraces, but Malt misses them. It's a pity which will cause me at least a full working day of work...

Maybe you can copy the logic from Pluto.PlutoRunner.CapturedException?

**Comment by schlichtanders** [comment]
I found the location which needs to be changed:
https://github.com/JuliaPluto/Malt.jl/blob/34e6226b80ee5f8a16ea0fb4ba5b41d0f00c6284/src/worker.jl#L80

Probably it is easiest to directly transform it to a string like it is done in a similar place
https://github.com/JuliaPluto/Malt.jl/blob/34e6226b80ee5f8a16ea0fb4ba5b41d0f00c6284/src/worker.jl#L126-L128

**Comment by Pangoraw** [comment]
> Or altrnatively delete the sprint transformations early on and do it during construction of Malt.RemoteException (or even better as showerror implementation of Malt.RemoteException)

The exception needs to be deserializable on the "main" process which is why we convert to string.
