### ISSUE TITLE
Equivalent of isrunning() for tasks?

### ISSUE THREAD

**Issue by droodman** [JuliaPluto/Malt.jl#73]
My feature suggestion might reflect a misunderstanding of the structure or goals of this package.

I would like to use Malt to provide an interface to Julia within another application (Stata) and make it interruptible, so that Ctrl-Break or the equivalent with Stata can stop a Julia command. To this end I want to dispatch a task asynchronously in Julia, then return control to code in Stata, that can check every 0.1 or 0.01 seconds whether the task is done, then get the results once it's done. I thought I would use `isrunning()` to check, without blocking, whether a task was complete. But that is for workers, not tasks.

Is it possible to add `isrunning()`-like functionality for tasks, i.e., a non-blocking function to check whether a task is finished?

**Comment by droodman** [comment]
I guess I can do something like

```
w = Malt.Worker()
t = Malt.remote_eval(w, :(done=false; sleep(10); done=true))
```
Then 
```
Malt.remote_eval_fetch(w, :done)
```
checks completion in a non-blocking way.

**Comment by fonsp** [comment]
If you start some work, then the returned value is a `Base.Task`, and you can call `Base.istaskdone` on it:

```julia
julia> w = Malt.Worker();

julia> Malt.remote_eval_wait(w, :(longtask() = sleep(10)))

julia> t = Malt.remote_eval(w, :(longtask()))
Task (runnable) @0x000000010a3a7d00

julia> istaskdone(t)
false

julia> sleep(10)

julia> istaskdone(t)
true

```

Does that work for your case?
