### ISSUE TITLE
Error on 1.11-rc1 when manually running a macro that references the calling module

### ISSUE THREAD

**Issue by disberd** [JuliaPluto/Malt.jl#77]
Hi, 
I have been noticing a lot of errors in the console where Pluto is started on julia 1.11 which do not happen in 1.10

This particular issue seems to be happening when manully running a macro in pluto which references the calling module.

Here is an example of the simplest reproducer:

https://github.com/JuliaPluto/Malt.jl/assets/12846528/d19ece80-dd96-4e38-81c6-f6af06a3b818

It does not seem to affect the Pluto results itself from my limited testing but it seems to happen on windows/linux/mac-os based on my CI tests [here](https://github.com/disberd/SimplePlutoInclude.jl/actions/runs/9780021050/job/27000657594)

**Comment by fonsp** [comment]
Do you think this is a Malt issue?

**Comment by disberd** [comment]
@fonsp I am not sure, I put it here at first because it was an error thrown from Malt but probably is caused by Pluto.
Unfortunately I tried shortly to debug this by creating programmaticaly a session with Pluto and execute the notebook cell from the REPL but in that case I could not reproduce the error
