### ISSUE TITLE
Tests: remote exceptions

### ISSUE THREAD

**Issue by fonsp** [JuliaPluto/Malt.jl#9]
What happens when a worker throws an exception during a remote call? Can we add tests for this behaviour?

**Comment by pankgeorg** [comment]
Does it make sense to test the whole Distributed suite - if the API is the same?

**Comment by savq** [comment]
> Does it make sense to test the whole Distributed suite - if the API is the same?

The API for Malt is much smaller, so it wouldn't make sense to test all the Distributed suite.
